---
dist: xenial
language: python
sudo: required
script:
  # check https://github.com/travis-ci/travis-ci/issues/1350
  - sudo sed -i '/^Defaults\tsecure_path.*$/d' /etc/sudoers
  - sudo apt-get -qq update
  - sudo apt-get install -y lxc lxc-templates debootstrap lxc-dev
  - pip install ansible
  - pip install -r test-requirements.txt
  - sudo -E molecule test -s lxc
